### PR TITLE
Bugfix/support 2016.1.2

### LINKED ISSUE #21: Incompatible with PHPStorm 2016.1.1
Today a patch release by Idea was issued. After applying PHPStorm reports that the plugin is incompatible.

Tested with plugin versions 1.2.1 and 1.3.1.

The event log output:

```
4:42:49 PM Plugin Error
           Problems found loading plugins:
           Following plugins are incompatible with current IDE build: PHPUnit Autocomplete Assistant
```

IDE version:

```
PhpStorm 2016.1.1
Build #PS-145.970, built on May 3, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

### PR DESCRIPTION
**Pull request by nusphere**
Add PHPStorm 2016.1.2 support and fixes #21

since the owner of this repo isn't active - pls check my working release at [my fork](https://github.com/shopfe/phpuaca/releases/tag/1.3.2-beta)

### CODE REVIEW

**Comment by nusphere** [comment]
also supports PhpStorm 2016.2 EAP

bildschirmfoto 2016-06-01 um 15 50 06

**Comment by maxfilatov** [comment]
@shopfe thanks!

**Comment by overgapo** [comment]
@shopfe, it looks like you deleted this fork, can you please return it, cause event 1.3.5 has no autocomplete for prophecy for me (2016.1, 2016.2)

**Comment by amakhrov** [comment]
@overgapo the fix from @shopfe has been merged to the main repo, so it should be included into the last released version of the plugin.

The issue you're talking about might be related to disabling type providers in the latest release (https://github.com/maxfilatov/phpuaca/issues/27#issuecomment-235221587). It's caused by limitations imposed by phpstorm, and requires some rework on the plugin.

**Pull request merged**
